version: "3.9"

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ["bun", "run", "dev"]
    ports:
      - "3000:3000"
    environment:
      NEXT_PRIVATE_DEMO_HOST: "http://host.docker.internal"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  demo-c:
    build: ./containers/c
    ports:
      - "7001:7001"

  demo-go:
    build: ./containers/go
    ports:
      - "7002:7002"

  demo-python:
    build: ./containers/python
    ports:
      - "7003:7003"
